spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cms_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your_jwt_secret_key
  expiration: 3600000
